add_endpoint_report() fix TypeError
TypeError: Cannot read property 'unwrap' of undefined
Co-Authored-By: liranmauda <liranmauda@users.noreply.github.com>
(cherry picked from commit 3a6a8b9b4f441a17212845c65e69999c4863aa8c)